export const pageCopy = {
  en: {
    chaosWords: [
      "🍺 100% CHICKEN",
      "🐔 0% COORDINASHUN",
      "💥 MAXIMUM CLUCK",
      "📺 PONS FAMLY APPROVD*",
      "🍗 BEST VIEEWED AFTER MIDNITE",
    ],
    tabMessages: [
      "$DRUNKCHICKEN is typign...",
      "helo holder u awake??? 🐔",
      "wen rich i spild the chart",
      "dont sell im still txting",
      "chikcen.exe had one beer",
      "wait wher is my portfoilo",
      "ok luv u holderss 🍗💸",
    ],
    reducedTitle: "$DRUNKCHICKEN 🍺 helo holderss",
    skip: "Skip to contract",
    announcementAria: "Important announcement",
    homeAria: "DRUNKCHICKEN home",
    navAria: "Primary navigation",
    navWhy: "WHY?",
    navManifesto: "MANIFSTO",
    online: "● ONLNE??",
    switchAria: "Switch to Traditional Chinese for Hong Kong",
    switchLabel: "繁中 HK",
    eyebrow: "★ THE INTERNET'S LEAST SOBER CHICKEN ★",
    languageAria: "Drunk chicken worldwide in Japanese and Chinese",
    worldWide: "WORLD WIDE WEB",
    shrineAria: "Anime chicken shrine warning",
    shrine: "WELCOME 2 MY CHIKEN SHRINE",
    breaking: "BREAKING!!!",
    launched: "LAUNCHED ON ROBINHOOD",
    newBadge: "NEW!",
    imageAlt: "The official DRUNKCHICKEN meme: a yellow chicken relaxing in an armchair with a beer",
    infomercialAria: "Drunkmaxxer, maxx profits",
    butWait: "★ BUT WAIT! ★",
    maxxProfits: "MAXX PROFITS*",
    officialMeme: "OFICIAL MEME — DO NOT FEED AFTER 2AM",
    asSeenAria: "As seen on Pons Family",
    asSeen: "BUT WAIT! AS SEEN ON",
    callNow: "📺 CALL NOW!!!",
    heroCopy: "One chicken. Several bevreges. Zero abiltiy to walk in a straight line.",
    tapeAuthentic: "AUTHENTIC CA",
    tapeCopy: "COPY THIS THING",
    contractTitle: "🍺 TOKEN_ADDRESS_FINAL_FINAL_IMDOINGITRIGHT_DRUNK_BLABLABLA.txt",
    contractLabel: "CONTRACT ADDRESS (CA)",
    copied: "✓ COPIED. CLUCK!",
    copyCa: "📋 COPY CA",
    getPons: "GET IT ON PONS FAMILY ↗",
    contractWarning: "CHECK THE FULL ADDRESS. THE CHICKEN CANNOT TYPE AND WILL NOT FIX YOUR MISTAKES.",
    legendOf: "THE LEGEND OF",
    drunkestChicken: "THE DRUNKEST CHICKEN",
    legendLine: "EVEN DRUNK, IT STILL CLUCKS.",
    cards: [
      ["THE PLAN??? 🐣", "Get drunk while the chicken moons. We get richer. Try to keep up. 🍻🌕"],
      ["THE IDEA 🐔", "One drunk chicken you bought while drunk, outperforming your entire portfolio. 🐔📈"],
      ["THE BEST BAD DECISION 🍻", "Buying one drunk chicken and getting rich. 🍗💸"],
    ],
    manifestoSticker: "4:07 AM // 12% BATTRY",
    manifestoFile: "🍺 drunkchikcen_unsent_FINAL_final_2.txt",
    manifestoTo: "TO: teh holderss 💚",
    manifestoDelivery: "delivred probably ✓✓",
    manifestoTitle: "THE DRUNKCHICKEN MANIFSTO",
    manifestoMessages: [
      ["helo holders its me. the drunk chiken. i foudn the phone behind couch and i have somthing importnat to say", "4:07 AM"],
      ["we are gona get rich becase i did the math on a napkin and the napkin said YES. i lost teh napkin but trust the proces probably", "4:08 AM"],
      ["RULE 1: hold the chicken. RULE 2: hold my drink. RULE 3: wait wich one was the token", "4:08 AM"],
      ["if chart go up: genius. if chart go down: chicken is just bending knees for a HUGE jump. this is sicence", "4:09 AM"],
      ["we dont leave holders at the bar. we cluck together. we drunkmaxx together. we wake up and check wallet with one eye together", "4:11 AM"],
    ],
    manifestoSignoff: "ok goodnite see u at the top or in the group chat asking what happend. luv, chicken xoxo",
    manifestoStamp: "GET RIHCH OR GET ANOTHR ROUND",
    manifestoFootnote: "*napkin math is not financal advice. the napkin has not been located.",
    finalAria: "Visit DRUNKCHICKEN on Pons Family",
    bottomInternet: "YOU HAVE REACHED THE BOTTOM OF THE INTERNET.",
    thirsty: "STILL THIRSTY?",
    enterPons: "🐔 ENTER PONS FAMILY 🐔",
    footerHq: "© 1994–FOREVER DRUNKCHICKEN WORLD WIDE WEB HEADQUARTERS",
    footerDisclaimer: "MEME TOKEN. NOT FINANCIAL ADVICE. DON'T DRINK AND TRADE.",
    visitorAria: "Fake visitor counter",
    visitor: "VISITOR # 000🍺420",
  },
  "zh-HK": {
    chaosWords: [
      "🍺 100% 醉雞",
      "🐔 0% 平衡感",
      "💥 最大咯咯能量",
      "📺 PONS FAMLY 認正咗掛*",
      "🍗 最好零晨後先睇",
    ],
    tabMessages: [
      "$DRUNKCHICKEN 打緊字...",
      "喂holder你瞓咗未??? 🐔",
      "幾時發達我倒瀉咗張chart",
      "唔好賣我仲打緊字",
      "醉雞.exe 飲多咗一罐",
      "等等我個portfoilo去咗邊",
      "ok愛你呀holderss 🍗💸",
    ],
    reducedTitle: "$DRUNKCHICKEN 🍺 喂holderss",
    skip: "跳去合約地址",
    announcementAria: "重要通告",
    homeAria: "DRUNKCHICKEN 首頁",
    navAria: "主要導覽",
    navWhy: "點解??",
    navManifesto: "宣言??",
    online: "● 上緊線??",
    switchAria: "切換至英文",
    switchLabel: "ENGLISH",
    eyebrow: "★ 全網最唔清醒嗰隻雞 ★",
    languageAria: "醉雞衝出日本、香港同全世界",
    worldWide: "萬維網",
    shrineAria: "動漫醉雞神壇警告",
    shrine: "歡迎入嚟我個醉雞神壇",
    breaking: "突發!!!",
    launched: "已經喺 ROBINHOOD 發射咗",
    newBadge: "新鮮!",
    imageAlt: "DRUNKCHICKEN 官方迷因：一隻黃色醉雞拎住啤酒攤喺梳化",
    infomercialAria: "醉雞MAXX，利潤MAXX",
    butWait: "★ 咪住先! ★",
    maxxProfits: "利潤 MAXX*",
    officialMeme: "官方 MEME — 凌晨2點後咪餵",
    asSeenAria: "Pons Family 見過佢",
    asSeen: "咪住！上過",
    callNow: "📺 即刻打嚟!!!",
    heroCopy: "一隻雞。幾罐飲品。完全行唔到直線。",
    tapeAuthentic: "正宗 CA",
    tapeCopy: "COPY 呢舊嘢",
    contractTitle: "🍺 代幣地址_最尾_真係最尾_今次啱掛_醉雞啦.txt",
    contractLabel: "合約地址 (CA)",
    copied: "✓ COPY咗。咯咯!",
    copyCa: "📋 COPY CA",
    getPons: "去 PONS FAMILY 買 ↗",
    contractWarning: "CHECK清楚成串地址。隻雞唔識打字，打錯都唔會幫你執。",
    legendOf: "傳說中嘅",
    drunkestChicken: "最醉嗰隻雞",
    legendLine: "就算飲醉，都仲識咯咯叫。",
    cards: [
      ["個計劃??? 🐣", "隻雞升月球嗰陣繼續飲。我哋愈飲愈有錢。跟貼啲。🍻🌕"],
      ["個橋 🐔", "飲醉嗰陣買落嘅一隻醉雞，跑贏你成個投資組合。🐔📈"],
      ["最佳壞決定 🍻", "買一隻醉雞，之後發達。🍗💸"],
    ],
    manifestoSticker: "凌晨 4:07 // 得返12%電",
    manifestoFile: "🍺 醉雞_未send_最尾_最尾2.txt",
    manifestoTo: "去: 各位holderss 💚",
    manifestoDelivery: "應該送到咗 ✓✓",
    manifestoTitle: "DRUNKCHICKEN 醉雞宣言",
    manifestoMessages: [
      ["喂各位holders係我呀。醉雞。我喺梳化底搵返部電話，而家有啲非講不可既重要嘢", "凌晨 4:07"],
      ["我哋會發達因為我用餐巾紙計過數，張紙話YES。我唔見咗張紙但個proces應該信得過", "凌晨 4:08"],
      ["規矩1：揸實隻雞。規矩2：幫我揸住杯嘢。規矩3：等陣邊樣先係token", "凌晨 4:08"],
      ["條chart升：我係天才。條chart跌：隻雞只係屈膝準備超級大跳。呢個係科學掛", "凌晨 4:09"],
      ["我哋唔會漏低holder喺酒吧。我哋一齊咯咯叫、一齊drunkmaxx、一齊用一隻眼開wallet", "凌晨 4:11"],
    ],
    manifestoSignoff: "ok早唞，山頂見；唔係就group chat問頭先發生咩事。愛你，醉雞 xoxo",
    manifestoStamp: "一係發達 一係再飲一ROUND",
    manifestoFootnote: "*餐巾紙數學唔係財務建議。張紙目前仍然失蹤。",
    finalAria: "去 Pons Family 睇 DRUNKCHICKEN",
    bottomInternet: "你已經去到互聯網最底。",
    thirsty: "仲口渴??",
    enterPons: "🐔 入去 PONS FAMILY 🐔",
    footerHq: "© 1994–永遠 DRUNKCHICKEN 萬維網總部",
    footerDisclaimer: "MEME TOKEN。唔係財務建議。飲咗酒咪交易。",
    visitorAria: "假嘅訪客計數器",
    visitor: "訪客 # 000🍺420",
  },
} as const;
