export const swapCopy = {
  en: {
    errors: {
      fallback: "The swap could not be completed.",
      cancelled: "Transaction cancelled in wallet.",
      insufficient: "Not enough ETH for the swap and gas.",
      moved: "Price moved too fast. Refresh the quote and try again.",
      rpc: "ROBINHOOD RPC IS BUSY. WAIT A FEW SECONDS, THEN KICK THE QUOTER AGAIN.",
      enterAmount: "Enter an ETH amount.",
      noBrowser: "No browser wallet found. Use WalletConnect QR or install an EVM wallet.",
      noAccount: "No wallet account selected.",
      wcConfig: "WalletConnect is not configured. Add NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID to .env.local.",
      approveChain: "Approve Robinhood Chain in WalletConnect, then try again.",
      connectFirst: "Connect a browser wallet or WalletConnect first.",
      approvalReverted: (asset: string) => `${asset} approval reverted onchain.`,
      transactionReverted: "The transaction reverted onchain.",
    },
    initial: "LIVE QUOTE FROM THE VERIFIED DRUNKCHICKEN POOL",
    quoteReady: (input: string, output: string) => `QUOTE READY ☆ ${input} → ${output} ON ROBINHOOD CHAIN`,
    lookingBrowser: "LOOKING FOR A BROWSER WALLET…",
    browserConnected: "BROWSER WALLET CONNECTED ☆ ROBINHOOD CHAIN READY",
    openingWc: "OPENING WALLETCONNECT QR… MOBILE CHICKENS INCOMING",
    wcDisconnected: "WALLETCONNECT DISCONNECTED. THE CHICKEN IS ALONE AGAIN.",
    wcConnected: "WALLETCONNECT LINKED ☆ ROBINHOOD CHAIN READY",
    forgotten: "WALLET FORGOTTEN. CONNECT AGAIN WHEN THE ROOM STOPS SPINNING.",
    buyMode: "BUY MODE… PICK ETH OR WETH AND AIM AT THE CHICKEN",
    sellMode: "SELL MODE… PICK WETH OR UNWRAPPED ETH",
    openingWallet: "OPENING WALLET… DO NOT FEED THE POP-UP",
    approving: (asset: string) => `APPROVE ${asset}… ONE WALLET CONFIRMATION BEFORE THE SWAP`,
    confirmSwap: "CONFIRM THE ONCHAIN SWAP IN YOUR WALLET",
    transactionSent: "TRANSACTION SENT… CHICKEN IS CROSSING THE CHAIN",
    success: "SUCCESS!!! DRUNKCHICKEN HAS ENTERED THE WALLET ☆彡",
    rail: "✦ CHICKEN SWAP SHOP ✦ BUY THE BIRD ✦ ૮₍˶• . • ⑅₎ა ✦ SWAP 4 CHIKEN NOW ✦",
    swapFile: "🐔 swap_DRUNK_final_FINAL2_use_this.exe",
    walletOffline: "WALLET: OFFLINE",
    browserShort: "BROWSER",
    directSwap: "DIRECT ONCHAIN SWAP",
    directionAria: "Swap direction",
    buyChicken: "BUY CHICKEN",
    sellChicken: "SELL CHICKEN",
    youPay: "YOU PAY",
    payAria: "Asset to pay",
    receive: "YOU RECEIVE (EST.)",
    receiveAria: "Asset to receive",
    calculating: "CALCULATING…",
    maxSlippage: "MAX SLIPPAGE",
    walletAria: "Choose wallet connection",
    searching: "SEARCHING…",
    browserWallet: "🦊 BROWSER WALLET",
    openingQr: "OPENING QR…",
    wcQr: "📱 WALLETCONNECT QR",
    adminWarning: "ADMIN: ADD NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID TO ENABLE QR CONNECTIONS.",
    connectedVia: "CONNECTED VIA",
    disconnect: "DISCONNECT",
    waiting: "WAIT 4 CHICKEN…",
    swapNow: "SWAP NOW!!!",
    connectButton: "CONNECT A WALLET FIRST",
    retryQuote: "🔄 KICK THE QUOTER AGAIN",
    receipt: "VIEW TRANSACTION RECEIPT ↗",
    disclaimer: "Uses the verified DRUNKCHICKEN / WETH pool and Robinhood Chain contracts. Your wallet signs the transaction through a browser wallet or WalletConnect; this site never sees private keys. ERC-20 routes may require approval first. ETH output unwraps WETH atomically. Quotes can move before confirmation.",
  },
  "zh-HK": {
    errors: {
      fallback: "個SWAP搞唔掂。隻雞甩咗手。",
      cancelled: "你喺wallet取消咗交易。",
      insufficient: "ETH唔夠畀SWAP同gas費。",
      moved: "個價走得太快。撳過報價再試。",
      rpc: "ROBINHOOD RPC 飲大咗。等幾秒，再踢個報價器一次。",
      enterAmount: "入個ETH數量先。",
      noBrowser: "搵唔到browser wallet。用WalletConnect QR或者裝個EVM wallet。",
      noAccount: "未揀wallet account。",
      wcConfig: "WalletConnect未設定。要喺.env.local加NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID。",
      approveChain: "喺WalletConnect批准Robinhood Chain，再試多次。",
      connectFirst: "先連browser wallet或者WalletConnect。",
      approvalReverted: (asset: string) => `${asset}批准喺chain上彈返轉頭。`,
      transactionReverted: "交易喺chain上彈返轉頭。",
    },
    initial: "DRUNKCHICKEN認證POOL即時報價緊",
    quoteReady: (input: string, output: string) => `報價到咗 ☆ ${input} → ${output} 喺 ROBINHOOD CHAIN`,
    lookingBrowser: "搵緊BROWSER WALLET…",
    browserConnected: "BROWSER WALLET連咗 ☆ ROBINHOOD CHAIN準備好",
    openingWc: "開緊WALLETCONNECT QR… 手機醉雞飛緊嚟",
    wcDisconnected: "WALLETCONNECT斷咗。隻雞又自己一個。",
    wcConnected: "WALLETCONNECT連咗 ☆ ROBINHOOD CHAIN準備好",
    forgotten: "WALLET唔記得咗。間房停低轉先再連。",
    buyMode: "買雞MODE… 揀ETH或者WETH再瞄準隻雞",
    sellMode: "賣雞MODE… 揀WETH或者拆返做ETH",
    openingWallet: "開緊WALLET… 唔好餵個POP-UP",
    approving: (asset: string) => `批准 ${asset}… SWAP前要wallet確認一次`,
    confirmSwap: "喺你個WALLET確認ONCHAIN SWAP",
    transactionSent: "交易送咗… 隻雞過緊CHAIN",
    success: "成功!!! DRUNKCHICKEN入咗你個WALLET ☆彡",
    rail: "✦ 醉雞交換所 ✦ 買隻雞 ✦ ૮₍˶• . • ⑅₎ა ✦ 即刻換雞 ✦",
    swapFile: "🐔 換雞_DRUNK_最尾_真係最尾.exe",
    walletOffline: "WALLET: 離線",
    browserShort: "瀏覽器",
    directSwap: "直接 ONCHAIN SWAP",
    directionAria: "選擇買雞或者賣雞",
    buyChicken: "買入醉雞",
    sellChicken: "賣出醉雞",
    youPay: "你要畀",
    payAria: "選擇付款資產",
    receive: "你會收到（估計）",
    receiveAria: "選擇收取資產",
    calculating: "計緊數…",
    maxSlippage: "最大滑點",
    walletAria: "選擇wallet連接方法",
    searching: "搵緊…",
    browserWallet: "🦊 BROWSER WALLET",
    openingQr: "開緊 QR…",
    wcQr: "📱 WALLETCONNECT QR",
    adminWarning: "ADMIN：加NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID先可以用QR連接。",
    connectedVia: "已連接：",
    disconnect: "斷開",
    waiting: "等隻雞陣…",
    swapNow: "即刻 SWAP!!!",
    connectButton: "先連接 WALLET",
    retryQuote: "🔄 再踢個報價器一次",
    receipt: "睇交易收據 ↗",
    disclaimer: "使用已認證嘅DRUNKCHICKEN / WETH pool同Robinhood Chain合約。交易由你個browser wallet或者WalletConnect簽署；本站永遠睇唔到private key。ERC-20路線可能要先批准。收ETH時會自動將WETH拆返。確認前報價可以郁。",
  },
} as const;
